repos:
    - repo: local
      hooks:
          - id: black
            name: black
            entry: poetry run black .
            language: system
            types: [python]
            require_serial: true
          - id: flake8
            name: flake8
            entry: poetry run flake8
            language: system
            types: [python]
            require_serial: true
          - id: pycln
            name: pycln
            description: "A formatter for finding and removing unused import statements."
            entry: poetry run pycln .
            language: system
            types: [python]
          - id: isort
            name: isort
            entry: poetry run isort
            require_serial: true
            language: system
            types_or: [cython, pyi, python]
            args: ["--filter-files"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-toml
            types: [toml]
          - id: check-yaml
            types: [yaml]
          - id: end-of-file-fixer
            types: [text]
            stages: [commit, push, manual]
          - id: trailing-whitespace
            types: [text]
            stages: [commit, push, manual]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.7.1
      hooks:
          - id: prettier
            types_or: [html, css, javascript]
